name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cargo cache
        uses: actions/cache@v4
        with:
            path: ~/.cargo/registry
            key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            restore-keys: |
                ${{ runner.os }}-cargo-

      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Cargo publish
        run: cargo publish
